# Dependencies
markdown            : redcarpet
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
highlighter         : pygments
gems                : ["jekyll-paginate"]
plugins             : [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Isaswa's Tech Blog
tagline:          'シッコクのブログ'
description:      'ソフトウェア開発、日常、アニメやゲームの考察や雑談などなど'
url:              http://isaswa.github.io
baseurl:          /

author:
  name:           'isaswa'
  url:            https://twitter.com/isaswa1602

paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/isaswa
twitter_username    : isaswa1602
github_username     : isaswa
youtube_username    : isaswa1602